// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentData() {
  return window['go']['main']['App']['GetCurrentData']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetLogfileText() {
  return window['go']['main']['App']['GetLogfileText']();
}

export function GetLogs10Sec(arg1) {
  return window['go']['main']['App']['GetLogs10Sec'](arg1);
}

export function GetLogs1Sec(arg1) {
  return window['go']['main']['App']['GetLogs1Sec'](arg1);
}

export function GetRuntimeConfig() {
  return window['go']['main']['App']['GetRuntimeConfig']();
}
