// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentData():Promise<main.OBDData>;

export function GetHealth():Promise<Record<string, any>>;

export function GetLogfileText():Promise<string>;

export function GetLogs10Sec(arg1:number):Promise<Array<Record<string, any>>>;

export function GetLogs1Sec(arg1:number):Promise<Array<Record<string, any>>>;

export function GetRuntimeConfig():Promise<Record<string, any>>;
